# Data Exploration

In [1]:
import pandas as pd
import numpy as np

## Reading Olympic File

In [2]:
oly_data = pd.read_csv('athlete_events.csv')

In [3]:
oly_data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [4]:
oly_data.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

## Isolating Women's Ice Hockey

In [5]:
oly_hockey = oly_data[oly_data['Event'].str.contains('Hockey')]
oly_hockey.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
28,9,Antti Sami Aalto,M,26.0,186.0,96.0,Finland,FIN,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
91,29,Willemien Aardenburg,F,22.0,NaN,NaN,Netherlands,NED,1988 Summer,1988,Summer,Seoul,Hockey,Hockey Women's Hockey,Bronze
247,123,Sohail Abbas,M,25.0,178.0,80.0,Pakistan,PAK,2000 Summer,2000,Summer,Sydney,Hockey,Hockey Men's Hockey,NaN
248,123,Sohail Abbas,M,29.0,178.0,80.0,Pakistan,PAK,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN

In [6]:
oly_ice_hockey = oly_data[oly_data['Sport'] == 'Ice Hockey']
oly_ice_hockey.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
28,9,Antti Sami Aalto,M,26.0,186.0,96.0,Finland,FIN,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
40,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
672,391,Clarence John Abel,M,23.0,185.0,102.0,United States,USA,1924 Winter,1924,Winter,Chamonix,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
673,392,George Gordon Abel,M,35.0,NaN,NaN,Canada,CAN,1952 Winter,1952,Winter,Oslo,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold
923,523,Trond Sevg Abrahamsen,M,19.0,183.0,87.0,Norway,NOR,1980 Winter,1980,Winter,Lake Placid,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN

In [7]:
oly_ih_w = oly_ice_hockey[oly_ice_hockey['Event'].str.contains('Women')]
oly_ih_w.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1334,753,Yurie Adachi,F,28.0,156.0,51.0,Japan,JPN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN
1885,1034,Viktoriya Adyeva,F,20.0,160.0,55.0,Kazakhstan,KAZ,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN
2126,1181,Meghan Christina Agosta (-Marciano),F,18.0,168.0,67.0,Canada,CAN,2006 Winter,2006,Winter,Torino,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
2127,1181,Meghan Christina Agosta (-Marciano),F,23.0,168.0,67.0,Canada,CAN,2010 Winter,2010,Winter,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
2128,1181,Meghan Christina Agosta (-Marciano),F,26.0,168.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold

In [8]:
oly_ih_w.shape

(754, 15)

## Exploring Women's Ice Hockey Table (oly_ih_w)

In [9]:
oly_ih_w.groupby('Team')['Name'].count()

Team
Canada           101
China             58
Finland           97
Germany           60
Italy             20
Japan             40
Kazakhstan        19
Russia            80
Slovakia          19
Sweden           100
Switzerland       59
United States    101
Name: Name, dtype: int64

In [10]:
oly_ih_w.groupby('Year')['Year'].count()

Year
1998    120
2002    156
2006    160
2010    160
2014    158
Name: Year, dtype: int64

#### ***2018 missing

In [11]:
oly_ih_w.groupby('Team')['Medal'].count()

Team
Canada           101
China              0
Finland           39
Germany            0
Italy              0
Japan              0
Kazakhstan         0
Russia             0
Slovakia           0
Sweden            40
Switzerland       19
United States    101
Name: Medal, dtype: int64

In [12]:
oly_medal_sum = oly_ih_w.groupby(['Year', 'Medal', 'Team'])['Team'].count()
oly_medal_sum

Year  Medal   Team
1998  Bronze  Finland          20
      Gold    United States    20
      Silver  Canada           20
2002  Bronze  Sweden           20
      Gold    Canada           20
      Silver  United States    20
2006  Bronze  United States    20
      Gold    Canada           20
      Silver  Sweden           20
2010  Bronze  Finland          19
      Gold    Canada           21
      Silver  United States    21
2014  Bronze  Switzerland      19
      Gold    Canada           20
      Silver  United States    20
Name: Team, dtype: int64

In [13]:
oly_medal_sum.reindex(index=['Gold', 'Silver', 'Bronze'], level='Medal')

Year  Medal   Team
1998  Gold    United States    20
      Silver  Canada           20
      Bronze  Finland          20
2002  Gold    Canada           20
      Silver  United States    20
      Bronze  Sweden           20
2006  Gold    Canada           20
      Silver  Sweden           20
      Bronze  United States    20
2010  Gold    Canada           21
      Silver  United States    21
      Bronze  Finland          19
2014  Gold    Canada           20
      Silver  United States    20
      Bronze  Switzerland      19
Name: Team, dtype: int64

In [14]:
US = oly_ih_w[oly_ih_w['Team'] == 'United States']
US

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
12646,6887,"Christina ""Chris"" Bailey",F,26.0,167.0,73.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
12647,6887,"Christina ""Chris"" Bailey",F,30.0,167.0,73.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
12909,7022,Laurie Baker (-Mutch),F,21.0,170.0,61.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
12910,7022,Laurie Baker (-Mutch),F,25.0,170.0,61.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
18226,9669,Kacey Lee Bellamy,F,22.0,170.0,66.0,United States,USA,2010 Winter,2010,Winter,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258319,129351,Kerry Pauline Weiland,F,29.0,163.0,62.0,United States,USA,2010 Winter,2010,Winter,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
258862,129604,"Kristen Elizabeth ""Krissy"" Wendell (-Pohl)",F,20.0,167.0,70.0,United States,USA,2002 Winter,2002,Winter,Salt Lake City,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
258863,129604,"Kristen Elizabeth ""Krissy"" Wendell (-Pohl)",F,24.0,167.0,70.0,United States,USA,2006 Winter,2006,Winter,Torino,Ice Hockey,Ice Hockey Women's Ice Hockey,Bronze
259906,130114,Sandra Whyte (-Sweeney),F,27.0,170.0,59.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
268021,134085,Jinelle Lynn Zaugg-Siergiej,F,23.0,183.0,80.0,United States,USA,2010 Winter,2010,Winter,Vancouver,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver

In [15]:
US.sort_values(by=['Year'], ascending=False)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
193978,97372,Josephine Pucci,F,23.0,173.0,68.0,United States,USA,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
35912,18446,"Alexandra ""Alex"" Carpenter",F,19.0,170.0,70.0,United States,USA,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
116428,58919,Amanda Kessel,F,22.0,165.0,64.0,United States,USA,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
121630,61501,Hilary Atwood Knight,F,24.0,180.0,79.0,United States,USA,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
59500,30475,Meghan Duggan,F,26.0,178.0,73.0,United States,USA,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142088,71277,Shelley Looney,F,26.0,165.0,64.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
52426,26939,Sara DeCosta (-Hayes),F,20.0,178.0,59.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
59950,30699,"Patricia ""Tricia"" Dunn-Luoma",F,23.0,173.0,66.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
119489,60489,"Kathryn ""Katie"" King",F,22.0,175.0,77.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
12646,6887,"Christina ""Chris"" Bailey",F,26.0,167.0,73.0,United States,USA,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold

In [16]:
Canada = oly_ih_w[oly_ih_w['Team'] == 'Canada']
Canada.sort_values(by=['Year'], ascending=False)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
132591,66741,Jocelyne Dawn Marie Larocque,F,25.0,170.0,63.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
255673,128002,"Jennifer Dorothy June ""Jenn"" Wakefield",F,24.0,175.0,77.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
130439,65665,"Charline ""Charlie"" Labont",F,31.0,175.0,72.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
158706,79680,Meaghan Mikkelson,F,29.0,175.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
109816,55524,Rebecca Ann Johnston,F,24.0,170.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92705,46974,Geraldine Anne Heaney,F,30.0,173.0,64.0,Canada,CAN,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
93059,47137,Jayna Hefford,F,20.0,163.0,63.0,Canada,CAN,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
115459,58494,"Rebecca D. ""Becky"" Kellar (-Duke)",F,23.0,170.0,71.0,Canada,CAN,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
174378,87573,Karen Anne Nystrom,F,28.0,168.0,63.0,Canada,CAN,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver
261592,130895,Stacy Eleanor Wilson,F,32.0,169.0,59.0,Canada,CAN,1998 Winter,1998,Winter,Nagano,Ice Hockey,Ice Hockey Women's Ice Hockey,Silver

In [17]:
Canada_2014 = oly_ih_w[(oly_ih_w.Team == 'Canada') & (oly_ih_w.Year == 2014)]
Canada_2014

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
2128,1181,Meghan Christina Agosta (-Marciano),F,26.0,168.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
8636,4742,Gillian Mary Apps,F,30.0,180.0,80.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
49183,25330,Melodie Daoust,F,22.0,163.0,71.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
71454,36383,Laura Michele Fortino,F,23.0,164.0,62.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
93063,47137,Jayna Hefford,F,36.0,163.0,63.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
103549,52392,Haley Lyn Irwin,F,25.0,170.0,78.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
107439,54296,Brianne Alexandra Jenner,F,22.0,175.0,70.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
109816,55524,Rebecca Ann Johnston,F,24.0,170.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
130439,65665,"Charline ""Charlie"" Labont",F,31.0,175.0,72.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
132591,66741,Jocelyne Dawn Marie Larocque,F,25.0,170.0,63.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
158706,79680,Meaghan Mikkelson,F,29.0,175.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
179278,90081,Caroline Ouellette,F,34.0,180.0,77.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
192269,96539,Marie-Philip Poulin,F,22.0,169.0,72.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
205002,102933,Lauriane Rougeau,F,23.0,173.0,75.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
226740,113937,Natalie Marie Spooner,F,23.0,178.0,80.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
233885,117307,Shannon Lynn Szabados,F,27.0,175.0,65.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
255673,128002,"Jennifer Dorothy June ""Jenn"" Wakefield",F,24.0,175.0,77.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
257035,128709,Catherine Ward,F,26.0,168.0,67.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
257456,128917,Tara Leigh-Anne Watchorn,F,23.0,178.0,76.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold
259992,130148,Hayley Marie Wickenheiser,F,35.0,178.0,77.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,Gold

#### ***No positions
#### ***Get rid of Sex, Season, Sport, Event
#### ***No actual stats
#### ***No number

In [18]:
Canada_2014.shape

(20, 15)

## Reading NWHL

In [19]:
NWHL_2017 = pd.read_excel('NWHL Skater and Team Stats 2017-18.xlsx', sheet_name='NWHL Skaters 201718')

In [20]:
NWHL_2017_po = pd.read_excel('NWHL Skater and Team Stats 2017-18.xlsx', sheet_name='NWHL Skaters 2018 Playoffs')

In [21]:
NWHL_Team = pd.read_excel('NWHL Skater and Team Stats 2017-18.xlsx', sheet_name='NWHL Team Stats')

In [22]:
NWHL_2017.head()

,No,Tm,Name,P,Ht,Rk,S,Age,Nat,GP,...,SH G,SH A,SH A1,SH P,SH P1,EN,Sh%,SOG/G,Pts/G,PIM
0,11,MET,Alexa Gruschow,F,"5'7""",NaN,R,23.0,USA,16.0,...,2.0,NaN,NaN,2.0,2.0,NaN,23.68,2.4,1.38,26.0
1,14,MET,Madison Packer,F,"5'9""",NaN,R,26.0,USA,12.0,...,NaN,1.0,NaN,1.0,0.0,NaN,22.73,3.7,1.50,10.0
2,14,BOS,Jillian Dempsey,F,"5'4""",NaN,L,26.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,16.28,2.7,0.94,2.0
3,18,MET,Rebecca Russo,F,"5'4""",NaN,L,23.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,1 ES,20.45,2.8,1.06,0.0
4,14,BUF,Hayley Scamurra,F,"5'8""",Y,L,22.0,USA,14.0,...,1.0,NaN,NaN,1.0,1.0,1 PP,11.11,4.5,1.00,16.0

#### RK= Rookie

In [23]:
NWHL_2017.shape

(86, 36)

In [24]:
NWHL_2017.columns

Index(['No', 'Tm', 'Name', 'P', 'Ht', 'Rk', 'S', 'Age', 'Nat', 'GP', 'SOG',
       'G', 'A', 'A1', 'P.1', 'P1', 'ES G', 'ES A', 'ES A1', 'ES P', 'ES P1',
       'PP G', 'PP A', 'PP A1', 'PP P', 'PP P1', 'SH G', 'SH A', 'SH A1',
       'SH P', 'SH P1', 'EN', 'Sh%', 'SOG/G', 'Pts/G', 'PIM'],
      dtype='object')

In [25]:
NWHL_2017_po.head()

,#,Tm,Name,P,Ht,Rk,S,Age,Nat,GP,...,SH G,SH A,SH A1,SH P,SH P1,EN,Sh%,SOG/G,Pts/G,PIM
0,2,BOS,Alyssa Gagliardi,D,"5'4""",NaN,L,25.0,USA,1.0,...,NaN,NaN,NaN,0,0,NaN,0.00,2.0,0.0,2.0
1,5,BOS,Lexi Bender,D,"5'8""",NaN,R,24.0,USA,1.0,...,NaN,NaN,NaN,0,0,NaN,33.33,3.0,1.0,NaN
2,6,BOS,Elizabeth Parker,D,"5'9""",*,L,26.0,USA,NaN,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
3,7,BOS,Mary Parker,F,"5'9""",Y,L,24.0,USA,1.0,...,NaN,NaN,NaN,0,0,NaN,0.00,4.0,2.0,NaN
4,8,BOS,Dana Trivigno,F,"5'4""",NaN,R,23.0,USA,1.0,...,NaN,NaN,NaN,0,0,NaN,0.00,5.0,0.0,2.0

In [26]:
NWHL_2017_po.shape

(86, 36)

In [27]:
NWHL_2017_po.columns

Index(['#', 'Tm', 'Name', 'P', 'Ht', 'Rk', 'S', 'Age', 'Nat', 'GP', 'SOG', 'G',
       'A', 'A1', 'P.1', 'P1', 'ES G', 'ES A', 'ES A1', 'ES P', 'ES P1',
       'PP G', 'PP A', 'PP A1', 'PP P', 'PP P1', 'SH G', 'SH A', 'SH A1',
       'SH P', 'SH P1', 'EN', 'Sh%', 'SOG/G', 'Pts/G', 'PIM'],
      dtype='object')

In [28]:
NWHL_2017.columns == NWHL_2017_po.columns

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [29]:
NWHL_Team

,Unnamed: 0,Unnamed: 1,First Quarter of the NWHL season,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,GP,W,L,OTL,PTS,GF,GA,G Diff,PP%,PK%,SF/GP,SA/GP,SF60,SA60,Tm Sv%,Sh%,PDO,FO%
1,Riveters,4,4,0,0,8,21,7,14,20,86.7,33.5,24.5,33.5,24.5,0.929,15.7,108.5,53.8
2,Beauts,4,2,2,0,4,13,17,-4,17.4,87,29.5,32,29.5,32,0.867,11,97.7,43.9
3,Whale,4,2,2,0,4,9,12,-3,8.3,78.3,25.25,32.25,24.73,31.6,0.907,7.9,98.6,47.6
4,Pride,4,0,3,1,1,8,15,-7,15.4,83.3,31.25,30.75,30.61,30.37,0.895,6.4,95.9,55
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,At the Holiday Break,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,GP,W,L,OTL,PTS,GF,GA,G Diff,PP%,PK%,SF/GP,SA/GP,SF60,SA60,Tm Sv%,Sh%,PDO,FO%
8,Riveters,7,7,0,0,14,33,11,22,26.3,91.3,33.57,22.86,33.57,22.86,0.931,14,107.1,53.3
9,Beauts,7,3,4,0,6,20,25,-5,17.6,82.4,27.29,34.57,27.29,34.57,0.897,10.5,100.2,45.76
10,Pride,7,2,4,1,5,18,22,-4,15,81.5,30.14,29.57,29.79,29.22,0.904,8.5,98.9,52.7
11,Whale,7,2,5,0,4,10,24,-14,5,75,26.14,30.14,25.84,29.79,0.886,5.4,94,48.32
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,At the All-Star Break,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,GP,W,L,OTL,PTS,GF,GA,G Diff,PP%,PK%,SF/GP,SA/GP,SF60,SA60,Tm Sv%,Sh%,PDO,FO%
15,Riveters,12,11,1,0,22,52,21,31,25,89.4,32.1,23.5,31.89,23.35,0.926,13.3,105.9,49.85
16,Beauts,12,8,4,0,16,33,34,-1,13.8,82,29.1,31.8,28.64,31.35,0.911,7.5,98.6,51.46
17,Whale,12,3,7,2,8,19,40,-21,7.7,78.8,26.3,29.8,25.56,29.05,0.888,6.1,94.9,49.08
18,Pride,12,2,6,4,8,24,33,-7,10.5,88,25.4,30.4,24.86,29.75,0.912,9.1,100.3,49.69
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,End of the 2017-18 NWHL season,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,GP,W,L,OTL,PTS,GF,GA,G Diff,PP%,PK%,SF/GP,SA/GP,SF60,SA60,Tm Sv%,Sh%,PDO,FO%
24,Riveters,16,13,3,0,26,64,30,34,25.6,88.5,30.75,23.31,30.61,23.2,0.92,13,105,52.17
25,Beauts,16,12,4,0,24,49,41,8,16.7,83.1,28.19,31.13,27.86,30.76,0.918,10.9,102.7,50.35
26,Whale,16,3,11,2,8,24,54,-30,7.3,76.1,26.5,27.81,25.97,27.26,0.879,5.7,93.6,48.69
27,Pride,16,4,8,4,12,33,44,-11,11.8,87.3,25.44,28.75,25.02,28.27,0.904,8.1,98.5,49.36

In [30]:
NWHL_Team.shape

(28, 19)

In [31]:
NWHL_Team.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'First Quarter of the NWHL season',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18'],
      dtype='object')

#### ***Teams needs to be cleaned up

### Exploring NWHL_2017 and NWHL_2017_po (playoffs) Further

In [32]:
NWHL_2017[NWHL_2017['Nat'] != 'USA']

,No,Tm,Name,P,Ht,Rk,S,Age,Nat,GP,...,SH G,SH A,SH A1,SH P,SH P1,EN,Sh%,SOG/G,Pts/G,PIM
12,8,CTW,Kelly Babstock,F,"5'7""",NaN,L,25.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,5.63,5.1,0.64,22.0
17,24,MET,Harrison Browne,F,"5'4""",NaN,L,24.0,CAN,15.0,...,1.0,NaN,NaN,1.0,1.0,NaN,13.64,1.5,0.60,8.0
18,7,MET,Tatiana Rafter,F,"5'10""",NaN,R,25.0,CAN,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,14.81,1.7,0.38,6.0
19,32,BUF,Jess Jones,F,"5'4""",*,L,27.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,13.79,2.1,0.64,11.0
20,26,BOS,Janine Weber,F,"5'8""",NaN,L,26.0,AUT,13.0,...,NaN,NaN,NaN,0.0,0.0,NaN,11.11,2.1,0.54,6.0
23,95,BUF,Taylor Accursi,F,"5'8""",Y,L,22.0,CAN,15.0,...,NaN,NaN,NaN,0.0,0.0,NaN,17.14,2.3,0.73,8.0
28,3,BUF,Sarah Edney,D,"5'6""",*,L,24.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,1 ES,10.34,2.1,0.43,6.0
36,17,CTW,Emma Greco,D,"5'9""",Y,L,22.0,CAN,6.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,1.0,0.33,2.0
37,21,CTW,Cydney Roesler,D,"5'9""",NaN,R,23.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,3.85,1.9,0.14,8.0
39,13,BOS,Kaleigh Fratkin,D,"5'7""",NaN,R,25.0,CAN,11.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,1.4,0.45,20.0
46,10,MET,Ashley Johnston,D,"6'0""",NaN,L,25.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,9.09,0.8,0.14,10.0
48,6,CTW,Shannon Doyle,D,"5'4""",NaN,R,25.0,CAN,15.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,2.0,0.33,16.0
50,25,CTW,Juana Baribeau,F,"5'7""",NaN,L,28.0,CAN,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,2.94,2.1,0.13,16.0
53,10,BUF,Sarah Casorso,D,"5'7""",NaN,L,25.0,CAN,15.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,1.3,0.60,17.0
54,12,BUF,Rebecca Vint,F,"5'10""",*,R,25.0,CAN,13.0,...,NaN,NaN,NaN,0.0,0.0,NaN,10.00,2.3,0.46,16.0
76,6,BUF,Jessica Sibley,F,"5'5""",Y,L,22.0,CAN,2.0,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.00,0.0

In [33]:
MET = NWHL_2017[NWHL_2017['Tm'] == 'MET']
MET

,No,Tm,Name,P,Ht,Rk,S,Age,Nat,GP,...,SH G,SH A,SH A1,SH P,SH P1,EN,Sh%,SOG/G,Pts/G,PIM
0,11,MET,Alexa Gruschow,F,"5'7""",NaN,R,23.0,USA,16.0,...,2.0,NaN,NaN,2.0,2.0,NaN,23.68,2.4,1.38,26.0
1,14,MET,Madison Packer,F,"5'9""",NaN,R,26.0,USA,12.0,...,NaN,1.0,NaN,1.0,0.0,NaN,22.73,3.7,1.50,10.0
3,18,MET,Rebecca Russo,F,"5'4""",NaN,L,23.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,1 ES,20.45,2.8,1.06,0.0
7,19,MET,Miye D'Oench,F,"5'4""",NaN,R,23.0,USA,9.0,...,NaN,1.0,1.0,1.0,1.0,1 ES,21.21,3.7,1.44,0.0
10,17,MET,Bray Ketchum,F,"5'8""",NaN,L,28.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,14.71,2.1,0.69,4.0
16,6,MET,Courtney Burke,D,"5'9""",NaN,L,23.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,4.88,2.6,1.19,12.0
17,24,MET,Harrison Browne,F,"5'4""",NaN,L,24.0,CAN,15.0,...,1.0,NaN,NaN,1.0,1.0,NaN,13.64,1.5,0.60,8.0
18,7,MET,Tatiana Rafter,F,"5'10""",NaN,R,25.0,CAN,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,14.81,1.7,0.38,6.0
21,55,MET,Kelsey Koelzer,D,"5'9""",Y,R,22.0,USA,14.0,...,NaN,1.0,1.0,1.0,1.0,NaN,17.86,2.0,1.00,10.0
25,2,MET,Erika Lawler,F,"4'11""",*,R,30.0,USA,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,4.17,1.7,0.57,10.0
32,5,MET,Jenny Ryan,D,"5'4""",Y,R,22.0,USA,16.0,...,NaN,1.0,1.0,1.0,1.0,NaN,6.12,3.1,1.00,8.0
33,26,MET,Kiira Dosdall,D,"5'9""",NaN,R,30.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,1.8,0.63,8.0
34,22,MET,Kelly Nash,F,"5'6""",*,R,28.0,USA,8.0,...,NaN,NaN,NaN,0.0,0.0,NaN,10.53,2.4,0.63,2.0
44,27,MET,Michelle Picard,D,"5'4""",NaN,L,24.0,USA,16.0,...,NaN,1.0,NaN,1.0,0.0,NaN,0.00,1.4,0.25,10.0
45,9,MET,Rebecca Morse,D|F,"5'8""",NaN,L,25.0,USA,13.0,...,1.0,NaN,NaN,1.0,1.0,NaN,13.33,1.2,0.15,2.0
46,10,MET,Ashley Johnston,D,"6'0""",NaN,L,25.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,9.09,0.8,0.14,10.0
47,21,MET,Lauren Wash,F,"5'4""",NaN,L,23.0,USA,5.0,...,NaN,NaN,NaN,0.0,0.0,NaN,25.00,0.8,0.20,0.0
63,20,MET,Cheeky Herr,F,"5'3""",NaN,R,23.0,USA,2.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,0.5,0.00,0.0
64,45,MET,Lindsey Hylwa,F,"5'9""",Y,R,23.0,USA,4.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,0.3,0.00,0.0
85,12,MET,Hillary Crowe,F,"6'0""",*,R,25.0,USA,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.0,0.00,0.0

In [34]:
MET_sort = MET.sort_values(by='No', ignore_index=True)
MET_sort

,No,Tm,Name,P,Ht,Rk,S,Age,Nat,GP,...,SH G,SH A,SH A1,SH P,SH P1,EN,Sh%,SOG/G,Pts/G,PIM
0,2,MET,Erika Lawler,F,"4'11""",*,R,30.0,USA,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,4.17,1.7,0.57,10.0
1,5,MET,Jenny Ryan,D,"5'4""",Y,R,22.0,USA,16.0,...,NaN,1.0,1.0,1.0,1.0,NaN,6.12,3.1,1.00,8.0
2,6,MET,Courtney Burke,D,"5'9""",NaN,L,23.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,4.88,2.6,1.19,12.0
3,7,MET,Tatiana Rafter,F,"5'10""",NaN,R,25.0,CAN,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,14.81,1.7,0.38,6.0
4,9,MET,Rebecca Morse,D|F,"5'8""",NaN,L,25.0,USA,13.0,...,1.0,NaN,NaN,1.0,1.0,NaN,13.33,1.2,0.15,2.0
5,10,MET,Ashley Johnston,D,"6'0""",NaN,L,25.0,CAN,14.0,...,NaN,NaN,NaN,0.0,0.0,NaN,9.09,0.8,0.14,10.0
6,11,MET,Alexa Gruschow,F,"5'7""",NaN,R,23.0,USA,16.0,...,2.0,NaN,NaN,2.0,2.0,NaN,23.68,2.4,1.38,26.0
7,12,MET,Hillary Crowe,F,"6'0""",*,R,25.0,USA,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.00,1.0,0.00,0.0
8,14,MET,Madison Packer,F,"5'9""",NaN,R,26.0,USA,12.0,...,NaN,1.0,NaN,1.0,0.0,NaN,22.73,3.7,1.50,10.0
9,17,MET,Bray Ketchum,F,"5'8""",NaN,L,28.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,14.71,2.1,0.69,4.0
10,18,MET,Rebecca Russo,F,"5'4""",NaN,L,23.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,1 ES,20.45,2.8,1.06,0.0
11,19,MET,Miye D'Oench,F,"5'4""",NaN,R,23.0,USA,9.0,...,NaN,1.0,1.0,1.0,1.0,1 ES,21.21,3.7,1.44,0.0
12,20,MET,Cheeky Herr,F,"5'3""",NaN,R,23.0,USA,2.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,0.5,0.00,0.0
13,21,MET,Lauren Wash,F,"5'4""",NaN,L,23.0,USA,5.0,...,NaN,NaN,NaN,0.0,0.0,NaN,25.00,0.8,0.20,0.0
14,22,MET,Kelly Nash,F,"5'6""",*,R,28.0,USA,8.0,...,NaN,NaN,NaN,0.0,0.0,NaN,10.53,2.4,0.63,2.0
15,24,MET,Harrison Browne,F,"5'4""",NaN,L,24.0,CAN,15.0,...,1.0,NaN,NaN,1.0,1.0,NaN,13.64,1.5,0.60,8.0
16,26,MET,Kiira Dosdall,D,"5'9""",NaN,R,30.0,USA,16.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,1.8,0.63,8.0
17,27,MET,Michelle Picard,D,"5'4""",NaN,L,24.0,USA,16.0,...,NaN,1.0,NaN,1.0,0.0,NaN,0.00,1.4,0.25,10.0
18,45,MET,Lindsey Hylwa,F,"5'9""",Y,R,23.0,USA,4.0,...,NaN,NaN,NaN,0.0,0.0,NaN,0.00,0.3,0.00,0.0
19,55,MET,Kelsey Koelzer,D,"5'9""",Y,R,22.0,USA,14.0,...,NaN,1.0,1.0,1.0,1.0,NaN,17.86,2.0,1.00,10.0

In [35]:
MET_po = NWHL_2017_po[NWHL_2017_po.Tm == 'MET']
MET_po

,#,Tm,Name,P,Ht,Rk,S,Age,Nat,GP,...,SH G,SH A,SH A1,SH P,SH P1,EN,Sh%,SOG/G,Pts/G,PIM
66,2,MET,Erika Lawler,F,"4'11""",*,R,30.0,USA,2.0,...,NaN,1.0,1.0,1,1,NaN,100.00,0.5,1.5,NaN
67,5,MET,Jenny Ryan,D,"5'4""",Y,R,22.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.5,0.0,NaN
68,6,MET,Courtney Burke,D,"5'9""",NaN,L,23.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.0,0.0,NaN
69,7,MET,Tatiana Rafter,F,"5'10""",NaN,R,25.0,CAN,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.5,0.0,NaN
70,9,MET,Rebecca Morse,D|F,"5'8""",NaN,L,25.0,USA,NaN,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
71,10,MET,Ashley Johnston,D,"6'0""",NaN,L,25.0,CAN,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.0,0.5,NaN
72,11,MET,Alexa Gruschow,F,"5'7""",NaN,R,23.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,14.29,3.5,0.5,NaN
73,12,MET,Hillary Crowe,F,"6'0""",*,R,25.0,USA,NaN,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
74,14,MET,Madison Packer,F,"5'9""",NaN,R,26.0,USA,2.0,...,1.0,NaN,NaN,1,1,NaN,25.00,2.0,1.5,4.0
75,17,MET,Bray Ketchum,F,"5'8""",NaN,L,28.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,50.00,1.0,0.5,NaN
76,18,MET,Rebecca Russo,F,"5'4""",NaN,L,23.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,25.00,2.0,1.0,NaN
77,19,MET,Miye D'Oench,F,"5'4""",NaN,R,23.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,2.5,1.0,NaN
78,20,MET,Cheeky Herr,F,"5'3""",NaN,R,23.0,USA,NaN,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
79,21,MET,Lauren Wash,F,"5'4""",NaN,L,23.0,USA,NaN,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
80,22,MET,Kelly Nash,F,"5'6""",*,R,28.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,33.33,1.5,0.5,NaN
81,24,MET,Harrison Browne,F,"5'4""",NaN,L,24.0,CAN,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.0,0.5,NaN
82,26,MET,Kiira Dosdall,D,"5'9""",NaN,R,30.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.5,0.0,4.0
83,27,MET,Michelle Picard,D,"5'4""",NaN,L,24.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,NaN,0.0,0.0,2.0
84,45,MET,Lindsey Hylwa,F,"5'9""",Y,R,23.0,USA,NaN,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN
85,55,MET,Kelsey Koelzer,D,"5'9""",Y,R,22.0,USA,2.0,...,NaN,NaN,NaN,0,0,NaN,0.00,1.0,0.5,2.0

## Reading CWHL

In [36]:
CWHL_2017 = pd.read_excel('CWHL Skater and Team Stats 2017-18.xlsx', sheet_name='Skaters')

In [37]:
CWHL_Team = pd.read_excel('CWHL Skater and Team Stats 2017-18.xlsx', sheet_name='Team Stats')

In [38]:
CWHL_2017.head()

,Name,#,Pos,Team,GP,G,A,A1,P,P1,...,PP P1,SH G,SH A,SH A1,SH P,SH P1,ENG,Pts/GP,PIM,Pl/Mi
0,Kate Leary,28,F,BOS,28.0,7.0,9.0,8.0,16.0,15.0,...,9.0,NaN,NaN,NaN,0.0,0.0,NaN,0.571429,18.0,-31.0
1,Meghan Grieves,17,F,BOS,28.0,6.0,8.0,6.0,14.0,12.0,...,8.0,NaN,NaN,NaN,0.0,0.0,NaN,0.500000,12.0,-32.0
2,Melissa Bizzari,23,F,BOS,25.0,4.0,8.0,7.0,12.0,11.0,...,5.0,1.0,NaN,NaN,1.0,1.0,NaN,0.480000,8.0,-22.0
3,Megan Myers,15,F,BOS,20.0,3.0,6.0,5.0,9.0,8.0,...,4.0,NaN,NaN,NaN,0.0,0.0,NaN,0.450000,10.0,-24.0
4,Michelle Ng,5,F,BOS,20.0,4.0,5.0,3.0,9.0,7.0,...,1.0,NaN,NaN,NaN,0.0,0.0,NaN,0.450000,12.0,-9.0

In [39]:
CWHL_2017.shape

(156, 29)

In [40]:
CWHL_2017.columns

Index(['Name', '#', 'Pos', 'Team', 'GP', 'G', 'A', 'A1', 'P', 'P1', 'ES G',
       'ES A', 'ES A1', 'ES P', 'ES P1', 'PP G', 'PP A', 'PP A1', 'PP P',
       'PP P1', 'SH G', 'SH A', 'SH A1', 'SH P', 'SH P1', 'ENG', 'Pts/GP',
       'PIM', 'Pl/Mi'],
      dtype='object')

#### ***7 columns diff than NWHL

In [41]:
CWHL_Team.head()

,CWHL,GP,W,L,OTL,SOL,PTS,OTW,GF/GP,GA/GP,...,RW,ROW,PPOP,PPGF,SHGA,PP%,TSH,PPGA,SHGF,PK%
0,LES CANADIENNES MONTREAL,28.0,22.0,5.0,0.0,1.0,45.0,3.0,4.035714,2.071429,...,15.0,18.0,116.0,26.0,0.0,0.224,129.0,16.0,6.0,0.876
1,KUNLUN RED STAR,28.0,21.0,6.0,0.0,1.0,43.0,2.0,3.392857,1.821429,...,18.0,20.0,93.0,20.0,0.0,0.215,105.0,13.0,3.0,0.876
2,CALGARY INFERNO,28.0,17.0,7.0,1.0,3.0,38.0,1.0,3.392857,2.392857,...,15.0,16.0,111.0,18.0,3.0,0.162,100.0,20.0,2.0,0.800
3,MARKHAM THUNDER,28.0,14.0,7.0,4.0,3.0,35.0,0.0,2.821429,2.321429,...,12.0,12.0,115.0,15.0,1.0,0.130,118.0,13.0,1.0,0.890
4,VANKE RAYS,28.0,14.0,13.0,0.0,1.0,29.0,0.0,2.642857,3.428571,...,10.0,10.0,109.0,15.0,4.0,0.138,103.0,17.0,2.0,0.835

In [42]:
CWHL_Team.shape

(13, 27)

In [43]:
CWHL_Team.columns

Index(['CWHL', 'GP', 'W', 'L', 'OTL', 'SOL', 'PTS', 'OTW', 'GF/GP', 'GA/GP',
       'Team Sv%', 'GF', 'actGF', 'GA', 'actGA', 'DIF', 'PIM', 'RW', 'ROW',
       'PPOP', 'PPGF', 'SHGA', 'PP%', 'TSH', 'PPGA', 'SHGF', 'PK%'],
      dtype='object')

### Exploring CWHL_2017 Further

#### ***No nationality

#### Other NWHL

In [45]:
NWHL_all = pd.read_csv('./NWHL/nwhl-scraper/nwhl_games_all.csv')

In [46]:
NWHL_all.head()

,Season,Player,Team,position,game_id,game_date,home_team,away_team,G,A1,...,SHG,SHA1,SHA2,FOW,FOL,PIM,Blk,TO,SV,GA
0,2015,Anya Battaglino,CTW,F|D,14665102,2016-08-18,CTW,MET,0,0,...,0,0,0,0,0,2,0,0,0,0
1,2015,Ashley Johnston,MET,D,14665102,2016-08-18,CTW,MET,0,0,...,0,0,0,0,0,2,0,0,0,0
2,2015,Brooke Ammerman,MET,F,14665102,2016-08-18,CTW,MET,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2015,Danielle Ward,CTW,F,14665102,2016-08-18,CTW,MET,0,0,...,0,0,0,0,0,2,0,0,0,0
4,2015,Elena Orlando,MET,D,14665102,2016-08-18,CTW,MET,0,0,...,0,0,0,0,0,2,0,0,0,0

In [47]:
NWHL_all.shape

(3862, 31)

In [48]:
NWHL_all.columns

Index(['Season', 'Player', 'Team', 'position', 'game_id', 'game_date',
       'home_team', 'away_team', 'G', 'A1', 'A2', 'PTS', 'PrPTS', 'GS', 'SOG',
       'eGF', 'eGA', 'GF.', 'PPG', 'PPA1', 'PPA2', 'SHG', 'SHA1', 'SHA2',
       'FOW', 'FOL', 'PIM', 'Blk', 'TO', 'SV', 'GA'],
      dtype='object')

In [49]:
NWHL_all.Season.nunique()

3

In [50]:
NWHL_all.Season

0       2015
1       2015
2       2015
3       2015
4       2015
        ...
3857    2017
3858    2017
3859    2017
3860    2017
3861    2017
Name: Season, Length: 3862, dtype: int64